JupiterOne/graph-jamf

jest.config.js, package.json, src/converters/entities/ComputerEntityConverter.test.ts, src/converters/entities/ComputerEntityConverter.ts, src/types.ts, yarn.lock
There appears to be a difference in the API response depending on the version of the Jamf server, though after further research, that isn't certain. I did some other content comparisons with output provided by another server and found that we also need to handle collections in a couple places around storage processing, so that is in here as well.
=> Handle storage device

CHANGELOG.md, package.json, yarn.lock
```
- Upgraded `@jupiterone/integration-sdk-*@6.0.0`, which includes a more
performant `jobState.findEntity()`.
```
=> Upgrade @jupiterone/integration-sdk-*@6.0.0

CHANGELOG.md, src/steps/devices/__snapshots__/converters.test.ts.snap, src/steps/devices/__snapshots__/index.test.ts.snap, src/steps/devices/converters.ts
- Update `_key` for `user_endpoint` to be the serial number of the computer
- Update `_key` for `mobile_device` to be the serial number of the mobile device
=> INT-1675 - Update the `_key` values of entities to be easily mappable

CHANGELOG.md, src/steps/devices/converters.ts, src/steps/devices/index.ts, src/steps/users/index.test.ts, src/steps/users/index.ts, src/util/device.ts, test/recording.ts
- `device_user` **HAS** `mobile_device`
- `device_user` **HAS** `user_endpoint`
=> Construct proper target entity `_key` for relationships

README.md
Also adds a link to issues repo.
=> Update README.md to latest pattern

CHANGELOG.md, docs/jupiterone.md, package.json, src/jamf/types.ts, src/steps/devices/__snapshots__/converters.test.ts.snap, src/steps/devices/converters.ts, test/mocks.ts, yarn.lock
Hi @austinkelleher !
Here's an update that should solve https://jupiterone.atlassian.net/browse/INT-2007
I actually don't have credentials for JAMF, so I did this based on their documentation:
https://developer.jamf.com/jamf-pro/reference/computer-inventory-1
If you want, you could test it by setting up extension attributes in our test account (if we have one?) using this:
https://docs.jamf.com/10.27.0/jamf-pro/administrator-guide/Computer_Extension_Attributes.html
Or send me credentials and I'll be happy to do it.
=> Adding extension attributes

CHANGELOG.md, src/steps/devices/index.ts
Added check to prevent duplicate relationships between jamf_computer_group and user_endpoint.
=> INT-1573 - Prevent duplicate relationships

.github/pull_request_template.md, .github/workflows/build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/gitleaks.yml, .github/workflows/questions.yml, .prettierignore, jupiterone/questions/questions.yaml, package.json, src/index.ts, src/util/toOSXConfigurationParsed.ts, tsconfig.dist.json
This PR updates workflows in `graph-jamf`, adds the `codeql-analysis` workflow, and `questions` workflow. This is a test for automatic syncing between the `integration-template` and `graph-*` projects.
=> Updating workflows, add codeql, add questions

jupiterone/questions/questions.yaml, package.json
Releasing as beta to make sure no imports are broken.
=> v2.7.1-beta.1

CHANGELOG.md, jupiterone/questions/questions.yaml, package.json
Release `v2.7.1` with new questions for `graph-jamf`.
=> Release-2.7.1 + Adding new questions

CHANGELOG.md, package.json
Version `graph-jamf` for dependency updates.
=> Release 2.7.5

.github/workflows/gitleaks.yml, CHANGELOG.md, package.json
=> Release 2.8.0

package.json, src/steps/users/index.ts
This is a preliminary pass at Jamf performance updates.  It batches user updates into groups of 10 and awaits all of them before continuing.
API
match the recommended model for …
=> INT-4492 - Jamf performance updates

CHANGELOG.md, package.json
=> Release 2.8.1

CHANGELOG.md, src/jamf/client.ts
Throw errors even if response is lacking details.
API …
=> Throw errors even if details are missing

.github/workflows/codeql-analysis.yml
- Run prettier on codeql-analysis.yml file so that the GitHub action pass (needed for NPM releases on two pending Jamf PRs).
API …
=> Run prettier on codeql-analysis.yml

.github/workflows/codeql-analysis.yml
Applies formatting to codeql-analysis.yml file
API …
=> Format codeql-analysis.yml

CHANGELOG.md, package.json
v2.9.0 release
API
relationships, and their property names, to …
=> Version 2.9.0

CHANGELOG.md, package.json
- Version 2.9.2
API
relationships, and their property names, …
=> Version 2.9.2

src/steps/accounts/__recordings__/fetchAccounts_3102900847/recording.har, src/steps/devices/__recordings__/fetchMacOsConfigurationDetails_496271272/recording.har, src/steps/groups/__recordings__/fetchGroups_39646731/recording.har, src/steps/users/__recordings__/fetchAdminUsers_595161074/recording.har
Modifying expiration on .har files for token so that we don't get test failures on replay.
API
reviewed all existing managed …
=> [NO-TICKET] - Fixing expired token issue on replays

CHANGELOG.md, package.json
- v2.10.0 release
API
relationships, and their property names, …
=> Version 2.10.0

CHANGELOG.md, package.json
=> Version 2.11.0

.gitignore, src/steps/users/__recordings__/fetchDeviceUsers_4008167391/recording.har, src/steps/users/__snapshots__/index.test.ts.snap, src/steps/users/index.ts
When fetch user by id fails instead of throwing an error it will log
API
relationships, and their property names, to ensure those questions still
function with my changes.
=> [INT-7471]: feat(users): log fetch user failure instead of throwing exception

src/jamf/client.ts, src/steps/devices/index.ts, src/steps/groups/index.ts, src/steps/users/index.ts, src/steps/users/interator.ts, src/steps/users/iterator.test.ts, test/mocks.ts
- Test `fetchUserById` 500 Error response
API
relationships, …
=> [INT-7470]: test fetchUserById 500 failure

.github/workflows/build.yml, .github/workflows/integration-deployment.yml, .gitignore, CHANGELOG.md, README.md, package.json, yarn.lock
Adding changes and new files to incorporate the package build and versioning to npm and raising a PR in integration-deployments to help with workflow efficiency.
=> INT-7815: adding auto package for builds

src/steps/groups/converters.ts, src/steps/groups/index.ts
=> Log sizes of fields of group entity

src/steps/devices/index.ts
=> Added wrapper to log the size of entities

src/steps/devices/index.ts, src/steps/groups/converters.ts, src/steps/groups/index.ts
=> Removed the logs added

.github/workflows/package-publish.yml
Forgot to copy in the updates to this workflow that I had tested locally. This should get it set right.
=> Fix Workflow

.github/workflows/package-publish.yml
=> Fix collector workflow
